services:
  - type: web
    name: yt-scrapper-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: PORT
        value: 8080
    autoDeploy: true